name: Validate CFF

on:
  push:
    paths:
      - "citation.CFF"
  workflow_dispatch:

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: cff-validator
        uses: dieghernan/cff-validator@v3
        with:
          install-r: true

